# Generated by Django 4.2 on 2023-05-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_apple_product_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apple_product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Iphones'), (2, 'Ipad '), (3, 'Apple Watch'), (4, 'MacBook'), (5, 'MacDesktop'), (6, 'AppleTV'), (7, 'AirBuds')], verbose_name='Category'),
        ),
    ]
