# Generated by Django 4.2 on 2023-05-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_alter_apple_product_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apple_Acceserise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('cat', models.IntegerField(choices=[(1, 'Iphones'), (2, 'Ipad '), (3, 'Apple Watch'), (4, 'MacBook'), (5, 'MacDesktop'), (6, 'AppleTV'), (7, 'AirBuds')], verbose_name='Category')),
                ('price', models.FloatField(verbose_name='Product Price')),
                ('status', models.BooleanField(default=True, verbose_name='Available')),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
