# Generated by Django 4.2 on 2023-05-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_apple_acceserise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apple_acceserise',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Iphones'), (2, 'Ipad '), (3, 'Apple Watch'), (4, 'MacBook'), (5, 'MacDesktop'), (6, 'AppleTV'), (7, 'AirBuds'), (8, 'Acceserise')], verbose_name='Category'),
        ),
    ]
