# Generated by Django 4.2 on 2023-05-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_alter_apple_acceserise_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apple_Acceserise',
        ),
    ]
