# Generated by Django 4.2 on 2023-05-19 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecomapp', '0007_delete_apple_acceserise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apple_product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Iphones'), (2, 'Ipad '), (3, 'Apple Watch'), (4, 'MacBook'), (5, 'MacDesktop'), (6, 'AppleTV'), (7, 'AirBuds'), (8, 'acceserise')], verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.apple_product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
